### ISSUE TITLE
Add other EFF wordlists

### ISSUE THREAD

**Issue by dijonkitchen** [grempe/diceware#15]
Would it make sense to add the two short lists too?

**Comment by grempe** [comment]
I think that at the moment I would refrain from this. While the short word list words are arguably easier to remember (since they max at 5 letters in a word) they also have less entropy per word, and are thus less secure for the same number of words when compared to the standard list which has 7776 words.

Also, all other lists are full word lists and there would have to be UI work done to explain the difference and calculate the entropy on a per list basis.

**Comment by dijonkitchen** [comment]
Per the EFF article, the short lists have shorter words that are easier to remember, but you'll need to use more words. 

Additionally, the second short list:

> Each word has a unique three-character prefix. This means that future software could auto-complete words in the passphrase after the user has typed the first three characters
> All words are at least an edit distance of 3 apart. This means that future software could correct any single typo in the user's passphrase (and in many cases more than one typo).

Reference: 
https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases

For the UI, is it possible to make it formulaic so that it can take the number of items in the JS object and recalculate those numbers?

**Comment by grempe** [comment]
I think the best approach if you want to support this is to add the functionality to https://github.com/lgaticaq/diceware-generator

I have contributed to this project, which pulls all of the random word selection into its own npm package with side loaded packages for each language or word list you want to support.

I will likely be converting to using this in the core of this Diceware UI as well in the not too distant future.

I think you would need to either embed metadata about the word list in the side package, or calculate it as you mentioned.

The auto-complete is a cool feature. You would probably want to add an additional API to that package to do lookups in the selected word list on the fly and return a match when you find one.

cc: @lgaticaq

**Comment by grempe** [comment]
I'll close this issue as it is more of a feature request that I don't think I want to support. Please feel free to comment if you disagree.

**Comment by dijonkitchen** [comment]
No worries. We can wait until you convert it over to using the generator.
