### ISSUE TITLE
word lists missing attribution / license issue

### ISSUE THREAD

**Issue by cfbao** [grempe/diceware#21]
Most (if not all) of the word lists used in this project are the same ones listed under [Diceware Home Page - Diceware in Other Languages](http://world.std.com/~reinhold/diceware.html#Diceware%20in%20Other%20Languages|outline). Many of which are licensed under a Creative Commons Attribution license. Some are under GNU GPL or GNU FDL license.
But I cannot find any attribution on this site.
Hope this can be fixed soon.

**Comment by grempe** [comment]
Addressed in 3cda8cfe12570970f926aea442d60767ef744d78

Thanks for the feedback and sorry for the delay.
