### ISSUE TITLE
Feature Request: Add Copy To Clipboard Button

### ISSUE THREAD

**Issue by ObfuscateTheWeb** [grempe/diceware#22]
I think it would be a neat feature to have a copy to clipboard button.

I think implementing it with [clipboard.js](https://clipboardjs.com/) would be a good idea.

Here's an example of it on [codepen](https://codepen.io/mburnette/pen/bVWaOO)

What do you guys think?

**Comment by lpraz** [comment]
Would `document.execCommand('copy')` be suitable in this case, just to avoid adding another dependency?

**Comment by ObfuscateTheWeb** [comment]
I don't really mind how it is implemented as long as it works. If  you think `document.execCommand('copy')` is suitable, then try and use it, if there's something I could help, please let me know

**Comment by grempe** [comment]
Thanks for the issue and the pull request. I manually applied it today.

24a7662688fd783b7a12c84fb070e4f9e6afb233

Cheers
