### ISSUE TITLE
Site claims dice rolls are biased

### ISSUE THREAD

**Issue by Freaky** [grempe/diceware#28]
Using mod to fit random values isn't safe - unless the values wrap perfectly you end up with bias towards the start of the range.

Here's 100 million dice rolls using `BYTE % 6`:

> [16792052, 16806014, 16789917, 16801670, **16413165**, **16397182**] stddev=202702

Having examined the code, this *isn't* what's happening.  So this bit is both alarming and misleading:

>  The Bytes output from the RNG are converted to die rolls with (BYTE % 6) + 1

**Comment by dhouck** [comment]
Yeah, I came here for the same reason. I'm glad the claim is false, but the text should clarify that this is handled correctly. 256 % 6 is 4, so based on the text I'd expect five and six to be slightly less likely. Given that you aren't actually going byte-by-byte *or* weighting the results incorrectly, this statement is just plain wrong.

**Comment by grempe** [comment]
Addressed by removing the outdated page text. Thanks for the report. 2fdc5a662d593ef03350e38f2d65b3f051d23e2a
