### ISSUE TITLE
EFF DragonCon wordlist 3D20

### ISSUE THREAD

**Issue by DonaldTsang** [grempe/diceware#36]
https://www.eff.org/deeplinks/2018/08/dragon-con-diceware
- [ ] Star Wars https://www.eff.org/files/2018/08/29/starwars_8k_2018.txt
- [ ] Star Trek https://www.eff.org/files/2018/08/29/memory-alpha_8k_2018.txt
- [ ] Game Of Thrones https://www.eff.org/files/2018/08/29/gameofthrones_8k-2018.txt
- [ ] Harry Potter https://www.eff.org/files/2018/08/29/harrypotter_8k-2018.txt

**Comment by atoponce** [comment]
Proposed improvements:

https://gist.github.com/atoponce/241abc6977dffeb6f9d724512e4fa339

**Comment by DonaldTsang** [comment]
@atoponce could you get me a Christmas present of forking the repo? Then we can start doing fun things.

**Comment by grempe** [comment]
Closing as this is not an actionable issue and seems to be providing info on an alternative passphrase approach.
