### ISSUE TITLE
Playing Cards Passwords method

### ISSUE THREAD

**Issue by DonaldTsang** [grempe/diceware#42]
http://www.webplaces.org/passwords/playing-cards-passphrase-method.htm
* Short version (10K): http://www.webplaces.org/passwords/lists/10k-word-list-short.txt
* long version (10K): http://www.webplaces.org/passwords/lists/10k-word-list-long.txt
* other version (10K): http://www.webplaces.org/passwords/lists/word-list-10k.txt
* Alternate: http://www.webplaces.org/passwords/lists/word-list-65555.txt

**Comment by atoponce** [comment]
(5304) Pokerware
- [ ] Formal https://github.com/skeeto/pokerware/blob/master/words-formal.txt
- [ ] Slang https://github.com/skeeto/pokerware/blob/master/words-slang.txt

**Comment by grempe** [comment]
Closing as this is not an actionable issue and seems to be providing info on an alternative passphrase approach.
