### ISSUE TITLE
Mnemonic Method (1626 triplets)

### ISSUE THREAD

**Issue by DonaldTsang** [grempe/diceware#43]
- [ ] SIA https://gitlab.com/NebulousLabs/entropy-mnemonics
- [ ] XMR https://github.com/monero-project/monero/tree/master/src/mnemonics
- [ ] Old Mnemonicode http://web.archive.org/web/20091003023412/http://tothink.com/mnemonic/wordlist.txt
- [ ] New Mnemonicode https://github.com/singpolyma/mnemonicode/blob/master/mn_wordlist.c

**Comment by grempe** [comment]
Closing as this is not an actionable issue and seems to be providing info on an alternative passphrase approach.
