### ISSUE TITLE
Use subresource integrity

### ISSUE THREAD

**Issue by brettcannon** [grempe/diceware#5]
[Subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) (SRI) lets you specify a hash for any content in a `<link>` or `<script>` tag to validate that what the browser gets is what you were expecting, e.g.:

```html
<script src="https://example.com/example-framework.js"
        integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
        crossorigin="anonymous"></script>
```

It's primarily useful for checking the integrity of files as served by a CDN (which I believe rempe.us/diceware is based on PR comments mentioning gh-pages). That way your  trust focuses primarily on what `index.html` is served to your browser as at least any directly loaded JS will be validated as the same as you expected to be served based on the hashes.

It's [supported](http://caniuse.com/#feat=subresource-integrity) by Chrome, Firefox, Opera, and Chrome Mobile so it isn't a waste of effort. And it supports hashes up to sha512 (which is what I would suggest using as sha384 truncates data which is only useful if you are trying to protect input values which isn't the case here).

The downside of SRI for a website that's entirely statically defined is that it means any time you update any JS code that is tagged with a hash you must also make sure to update the hash. That probably means adding a step in the development process for anyone who edits any JS as they will need to update the appropriate hash(es). Having said all of this, I am willing to pull together a Python script that you can point at an HTML file and have it print out when the hashes are outdated and what the new hash values should be (I would make a new GH project for this and license it under Apache 2 if you wanted to embed a copy in this repo). There are also SRI-generating tools for things like Gulp if that's how you would want to do your workflow.

**Comment by grempe** [comment]
Good suggestion.  I had thought about it as well, but had not gotten around to it.

I wrote a script in Ruby that I put in the top level dir. It generates a JSON file which I also committed that has the hashes for every JS/CSS file in the repo.  This can be run on every update.  Then its just a matter of copying the hash into the index.html file.  A bit of a pain, but most of the JS files in this project should never change (the word lists).

Any further suggestions on improving this welcome.

I'll push it out and test it with Chrome and some of the SRI testing tools out there now to make sure its ok.  I tested with a local web server and Chrome and all seemed good.

**Comment by grempe** [comment]
100% score on the first go-around. :-)

https://sritest.io/#report/e0d1efa0-cc91-46d9-9450-8669cfe3bfe2

**Comment by brettcannon** [comment]
So one thing you could do is load the JSON file prior to running, do the calculations, and on any hashes the differ, print out the differences so that you are explicitly told which files have changed (while I expect you will know ahead of time what you changed, it doesn't hurt to have the reminder either).
