### ISSUE TITLE
Megalists

### ISSUE THREAD

**Issue by DonaldTsang** [grempe/diceware#50]
https://kevinmarquette.github.io/2017-03-25-mnemonic-wordlist
https://github.com/singpolyma/mnemonicode and https://github.com/bwhmather/python-mnemonicode
http://bohwaz.net/archives/web/Bubble_Babble.html and http://www.wiki.yak.net/589
https://github.com/kpalin/bubblebabblepy and https://github.com/zougloub/python-bubblebabble
https://github.com/rsaarelm/vorud and https://github.com/dsw/proquint
https://github.com/cynodelic/bitspeak
https://github.com/femto113/node-pronounceable and https://github.com/flon-io/mnemo
https://github.com/jmettraux/rufus-mnemo and https://github.com/jmettraux/munemo
https://github.com/alexvandesande/Daefen
https://github.com/mgrp/phonobyte
https://gist.github.com/amintos/4507279
https://github.com/paulbellamy/base65536
https://github.com/ssut/basehangul
https://github.com/anexia-it/go-human
https://github.com/imuli/word-bases
https://github.com/mattdot/basehuman
https://maksverver.github.io/key-encoding/
https://github.com/mgrp/humanencoding
https://github.com/andyburke/simplecoder
https://github.com/gfredericks/hexes
https://github.com/lpil/wordhash
https://github.com/DrDub/namegen
https://github.com/nimakha/humanhash
https://github.com/fpgaminer/hash-phrase
https://github.com/jjt/hashwords
https://github.com/wolfeidau/humanhash
https://github.com/JakeElder/reversible-human-readable-id
https://github.com/jasonkester/hashid32
https://github.com/supertramped/vw-lda-wrapper
https://github.com/zacharyvoase/humanhash
https://github.com/rcorp/bhasha
https://github.com/jamesmunns/human-hash-rs
https://github.com/fxnn/readable-hash
https://github.com/fpgaminer/hash-phrase
https://github.com/davidmarkclements/hash-phrase

**Comment by grempe** [comment]
Closing as this is not an actionable issue and seems to be providing info on an alternative passphrase approach.
