### ISSUE TITLE
Allow for bookkeeping a specific wordlist

### ISSUE THREAD

**Issue by brettcannon** [grempe/diceware#6]
When you choose a wordlist other than "English" there's no way to always go back to the website from a bookmark and have that wordlist selected. Probably changing it so that when a different wordlist was selected the URL was rewritten to have e.g. `#english-alt` and have some JS to parse the URL and select the wordlist appropriately would be required.

**Comment by grempe** [comment]
I like the idea. I think I'll wait for a pull request on this one though.  I've been toying with the idea of converting this app to Elm (which would likely mean moving away from Bootstrap for it also) so I'm a bit reluctant to dig into whether this is possible without a bunch of research and implementation time that might be wasted. :)

**Comment by brettcannon** [comment]
I think a change in `$(document).ready()`, `$('.listSelectionLink').on('click')`, and `resetUI()` should be all that is needed. 

But how serious are you about using [Elm](http://elm-lang.org/)? If you're very serious I can postpone until it happens, otherwise I can go ahead and hack something together now.

**Comment by grempe** [comment]
Well, lets put it this way.  I've thought about it. But no immediate action
planned on that.  So if you'd like to do a pull request I'd certainly
entertain that.  Thanks!

**Comment by grempe** [comment]
Nice addition Brett.  Thanks for the pull request.  I've pushed it out to master and gh-pages branches.  Should be available shortly.  Cheers.

**Comment by brettcannon** [comment]
Welcome! And that finished my wishlist! :tada:
