### ISSUE TITLE
Mobile site has no way to submit entered numbers

### ISSUE THREAD

**Issue by brettcannon** [grempe/diceware#9]
I just discovered I made a major boo-boo when adding the `tel` support to the input field; there's no return/enter key on the numeric keypad under Android. All there is is a "next" button to go to the next field in the form (which happens to just be a link on the website). So without adding a submit button (maybe the `#` symbol next to the input field?), the `tel` type should be removed.

**Comment by grempe** [comment]
Reverted commit, but kept autofocus behavior when resolving revert merge conflict.

**Comment by grempe** [comment]
Thanks for noticing the issue @brettcannon 

I appreciate the follow up.
